# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:47
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listdet', '0003_auto_20171117_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
    ]
