# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:29
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listdet', '0004_post_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='类别')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
